name: Mine Hoosat Coin

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mine:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up mining software
      run: |
        choco install -y git
        git clone https://github.com/Lolliedieb/lolMiner-releases.git
        cd lolMiner-releases
        copy lolMiner.exe C:\

    - name: Run miner
      run: |
        set POOL=eu.mining4people.com:3390
        set WALLET=hoosat:qz4534l97cut3j2q0dljq8hc2vvgrpx8wgcm3q7edtt8ty3vsw8sxhw72eyla.timohoosat1
        set EXTRAPARAMETERS=--apiport 8020
        set MyVariable=C:\lolMiner.exe
        cd C:\
        echo "Running lolMiner from %MyVariable%"
        %MyVariable% --algo PYRIN --pool %POOL% --user %WALLET% --watchdog exit %EXTRAPARAMETERS%

    - name: Cleanup
      run: |
        del C:\lolMiner.exe
